j256/ormlite-core

- src/main/java/com/j256/ormlite/misc/SqlExceptionUtil.java
- src/test/java/com/j256/ormlite/misc/SqlExceptionUtilTest.java
The problem is that if you pass `SQLException` as a cause, user does not get the `SQLState` provided by the cause and has to check and cast type manually to obtain SQL error code. This may be quite tiresome and slightly hardens debugging.
> Pass SQLException#SQLState to next SQLException

- src/main/java/com/j256/ormlite/db/BaseDatabaseType.java
- src/main/java/com/j256/ormlite/field/SqlType.java
- src/main/java/com/j256/ormlite/field/types/UuidType.java
This is intended to use the UUID for PostgreSQL and UNIQUEIDENTIFIER for MSSQL as native sql datatypes. Please see the additional pull request in the jdbc as well.
> Added UUID as a Specific SQL Type

- pom.xml
See for details: http://mail.openjdk.java.net/pipermail/build-infra-dev/2013-January/002899.html
> Javadocs weren't generated under Java 8.

- src/main/java/com/j256/ormlite/stmt/Where.java
Allow Where to be extended, so that a sub class can perform validation on clauses.
Basically, I want to create a SafeWhere that wraps any String like Object in the eq and like methods in a SelectArg
> Make Where.java constructor be protected

- src/main/java/com/j256/ormlite/dao/BaseDaoImpl.java
- src/main/java/com/j256/ormlite/dao/Dao.java
- src/main/javadoc/doc-files/changelog.txt
If multiple threads used createOrUpdate() or createIfNotExists(), race conditions could result.  Added synchronized keyword.
> Add synchronized to createOrUpdate() and createIfNotExists() dao methods 

- src/main/doc/ormlite.texi
- src/main/java/com/j256/ormlite/dao/BaseDaoImpl.java
- src/main/java/com/j256/ormlite/field/DatabaseField.java
- src/main/java/com/j256/ormlite/field/DatabaseFieldConfig.java
- src/main/java/com/j256/ormlite/field/DatabaseFieldConfigLoader.java
- src/main/java/com/j256/ormlite/field/ForeignCollectionField.java
- src/main/javadoc/doc-files/changelog.txt
- src/test/java/com/j256/ormlite/field/DatabaseFieldConfigLoaderTest.java
In SQLite (maybe others) there are times when @DatabaseField(columnDefinition="...") isn't enough and the field name needs to be embedded in some special SQL.  Added a fullColumnDefinition that doesn't just append a definition string to the field name.
> Add full column definition

- src/main/java/com/j256/ormlite/table/DatabaseTableConfig.java
- src/main/java/com/j256/ormlite/table/TableInfo.java
From Java 7 javadocs:
> public String toLowerCase()
> Note: This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, "TITLE".toLowerCase() in a Turkish locale returns "t\u0131tle", where '\u0131' is the LATIN SMALL LETTER DOTLESS I character. To obtain correct results for locale insensitive strings, use toLowerCase(Locale.ENGLISH). 
Fix for #87 #67 #108
> Fix the problem with Turkish locale

- src/main/java/com/j256/ormlite/dao/BaseDaoImpl.java
- src/test/java/com/j256/ormlite/dao/BaseDaoImplTest.java
TableInfo is always populated, unlike TableConfig. Fixes issue #94.
> Get table name from TableInfo

- src/main/java/com/j256/ormlite/stmt/QueryBuilder.java
Currently if you have an order by or group by clause in a joined query it will be applied to the main query. However, if you join twice, and you nest the joins, as in this example:
```
QueryBuilder queryA = daoA.queryBuilder();
QueryBuilder queryB = daoB.queryBuilder();
QueryBuilder queryC = daoC.queryBuilder();
queryC.orderBy("column", true);
queryB.join(queryC);
queryA.join(queryB);
```
The outmost query will not be sorted by "column". Instead, the orderBy will be completely ignored.
This pull request is intended to fix that.
> Recursively apply order by and group by in joined queries

- src/main/java/com/j256/ormlite/dao/CloseableIterator.java
- src/main/java/com/j256/ormlite/dao/EagerForeignCollection.java
- src/main/java/com/j256/ormlite/stmt/SelectIterator.java
- src/main/javadoc/doc-files/changelog.txt
- src/test/java/com/j256/ormlite/dao/BaseDaoImplTest.java
Not sure why `moveAbsolute(...)` was missing from this list since it is supported by the underlying `DatabaseResults`.
> Added support for CloseableIterator.moveAbsolute(...)

- src/main/java/com/j256/ormlite/field/FieldType.java
- src/main/javadoc/doc-files/changelog.txt
- src/test/java/com/j256/ormlite/field/FieldTypeTest.java
Fixed problem with a field assigning that failed then causing a NPE because of a null pointer dereference.  Thanks to @hrach.
> Fixed NPE if assigning null to a primitive type

- src/main/java/com/j256/ormlite/field/types/ByteArrayType.java
When using the default implementation, `getBytes()` was appending additional bytes to the results.
> Enable users to set a character set for byte array type.

- src/main/java/com/j256/ormlite/stmt/Where.java
Allows building things like:
`dao.queryBuilder().leftjoin(dao2.queryBuilder().where().queryBuilder()).queryForFirst();`
> Allow retrieval of QueryBuilder from Where

- src/main/java/com/j256/ormlite/db/BaseDatabaseType.java
There's not too much reason for these to be the only ones that are private. While the need to override these methods will not be common, it does allow for the likes of example 1 in https://github.com/j256/ormlite-core/issues/20#issuecomment-443361114 to be possible.
> Exposed BaseDatabaseType's int, float and double type string appenders to protected

- src/main/java/com/j256/ormlite/field/types/BigIntegerType.java
This would error on databases which did not accept `VARCHAR(0)`.
> Fixed default width not being applied for BigInteger

- src/main/java/com/j256/ormlite/stmt/StatementExecutor.java
- src/test/java/com/j256/ormlite/stmt/StatementExecutorTest.java
The [default behaviour](https://github.com/j256/ormlite-core/blob/e41f83a5a5ec8aec42ea6f30630ae0a8130a7c8f/src/main/java/com/j256/ormlite/support/BaseConnectionSource.java#L70) of `saveSpecialConnection` is to use a something similar to a reference counter. Unless I'm mistaken, that means that every call `saveSpecialConnection` _must_ later follow with a call to `clearSpecialConnection` _regardless_ of the return value of the former.
> Always clear special connection on batch tasks

- src/main/java/com/j256/ormlite/dao/BaseDaoImpl.java
Before this change, it could happen that two threads retrieve the same iterator, leading to unexpected behavior.
> Fixing a severe concurrency issue when using an iterator

- src/main/java/com/j256/ormlite/db/BaseDatabaseType.java
- src/main/java/com/j256/ormlite/field/types/BooleanCharType.java
- src/test/java/com/j256/ormlite/db/BaseCoreDatabaseTypeTest.java
Two fixes. The most important I'd say is the first one.
1. **BooleanNumberFieldConverter**: The purpose of this was to convert a boolean to a number, but the class declares it is storing a boolean! This caused exceptions with its use in Derby.
SQLite, which I imagine is what this was originally made for, seemed to cope okay with it in its JDBC driver. I don't believe this is going to cause any issues since `BOOLEAN` maps to `NUMERIC` in SQLite which means "any type" over there. I have not tested Android, sorry, but I would be surprised if there were issues there.
2. **BooleanCharType**: the purpose of this class is to convert to a `CHAR` rather than a `VARCHAR`. The few JDBC drivers I've looked at work with char and String in either type so it didn't cause really any driver-level issues …
> Fixed a couple of incorrect SqlTypes in field converters

- src/main/java/com/j256/ormlite/misc/JavaxPersistenceImpl.java
- src/test/java/com/j256/ormlite/misc/JavaxPersistenceTest.java
This is what is used to declare foreign collections.
Instead of implementing the OneToMany annotation, OneToOne and ManyToOne seemed to have code checking if it is a collection. This doesn't make any sense to me but I've left it there and just added OneToMany. Perhaps the old behaviour can be formally deprecated.
> Added support for the OneToMany JPA annotation

- src/main/java/com/j256/ormlite/dao/EagerForeignCollection.java
- src/main/java/com/j256/ormlite/dao/LazyForeignCollection.java
- src/main/javadoc/doc-files/changelog.txt
- src/test/java/com/j256/ormlite/dao/LazyForeignCollectionTest.java
> Added some improvements to eager/lazy foreign collections.  Fixes #141

- pom.xml
- src/main/java/com/j256/ormlite/logger/Log4j2Log.java
- src/main/java/com/j256/ormlite/logger/Log4jLog.java
- src/main/javadoc/doc-files/changelog.txt
- src/test/java/com/j256/ormlite/logger/Log4jLogTest.java
- src/test/java/com/j256/ormlite/logger/LoggerFactoryTest.java
Also fixed a problem with the wiring of the log4j that would cause them to not be found.
> Move the log4j classes to core.  Thanks to @MarcMil.

- src/main/java/com/j256/ormlite/dao/BaseDaoImpl.java
- src/main/java/com/j256/ormlite/dao/Dao.java
- src/main/java/com/j256/ormlite/misc/functional/Supplier.java
Using `Dao#createIfNotExists(T)` can be inefficient due to object creation. A likely scenario is that the object is constantly being created, but almost never used, since the database already contains one.
I added `Dao#createIfNotExists(ID, Supplier<T>)` to be able to call this method with lazy initialization. In this case, the object will be created only when there is a real need.
Since the project uses Java 7, there are no functional interfaces like `Supplier`. So I implemented it myself in `misc.functional`. A similar approach is also taken by log4j. Users on Java 8+ will be able to use it as a full functional interface. On versions below, this will also be used without problems, but without lambdas, of course.
The implementation of `BaseDaoImpl#createIfNotExists(T)` has now also been …
> Add lazy variant of Dao#createIfNotExists

- src/test/java/com/j256/ormlite/table/DatabaseTableConfigTest.java
Fixed a non deterministic test DatabaseTableConfigTest.
To reproduce the problem, first build the project 
> mvn install -am -DskipTests
To identify the non deterministic test, execute the following [nondex](https://github.com/TestingResearchIllinois/NonDex) command:
> mvn edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=com/j256/ormlite/table/DatabaseTableConfigTest#testMultiAfter
The test is non deterministic likely due to the reliance on the order of FieldType objects returned by the getFieldTypes() method. 
If the getFieldTypes() method returns the fields in a non-deterministic or unpredictable order, the test's assertions, which expect a specific order (i.e., FIELD_NAME3, FIELD_NAME1, FIELD_NAME2), may fail intermittently when the order of the fields changes between test runs. …
> fixed the non deterministic behaviour of DatabaseTableConfigTest

- src/main/java/com/j256/ormlite/logger/BaseLogger.java
- src/test/java/com/j256/ormlite/logger/LoggerFactoryTest.java
The logger backend is sometimes set to null in the `LoggerFactoryTest`, which can cause other tests to fail when the order of test execution is changed.
Such failures could be provoked by these commands:
```sh
mvn clean test -Dtest=RuntimeExceptionDaoTest#testCallBatchTasksThrow,LoggerFactoryTest#testSetLogFactory
mvn clean test -Dtest=RuntimeExceptionDaoTest#testCallBatchTasksThrow,LoggerFactoryTest#testLogFactoryAsClass
```
This PR intends to fix these order dependencies by resetting the `LogBackend` after each test.
> Fix test order dependencies in LoggerFactoryTest
